# Generated by Django 6.1.1 on 2026-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(default='support@company.local', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('support', 'Customer Support'), ('billing', 'Billing & Invoicing'), ('sales', 'Sales Inquiry'), ('technical', 'Technical Support'), ('general', 'General Inquiry'), ('spam', 'Spam / Junk'), ('unclassified', 'Unclassified')], default='unclassified', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI Confidence score (0.0 to 1.0)', null=True)),
                ('assigned_department', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('classified', 'Classified'), ('routed', 'Routed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Record',
                'verbose_name_plural': 'Email Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
