# Generated by Django 6.1.1 on 2026-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('Technical Support', 'Technical Support'), ('Billing', 'Billing'), ('Complaint', 'Complaint'), ('Sales', 'Sales'), ('Account & Access', 'Account & Access'), ('General Inquiry', 'General Inquiry')], default='General Inquiry', max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=20)),
                ('confidence', models.FloatField(default=0.85, help_text='Classification confidence percentage (e.g. 92.5)')),
                ('department', models.CharField(default='General Support Team', max_length=150)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Classification',
                'verbose_name_plural': 'Email Classifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailRecord',
        ),
    ]
