# Generated by Django 6.1.1 on 2026-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailclassification_delete_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclassification',
            name='engine',
            field=models.CharField(default='AI (LLM)', help_text='AI Provider/Model or Fallback mechanism', max_length=100),
        ),
    ]
