"""
Django settings for email_classifier project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from email_classifier.environment import load_local_environment


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from local .env when available.
load_local_environment()


# ============================================================
# SECURITY / DEPLOYMENT SETTINGS
# ============================================================

# DEBUG is enabled only when explicitly requested.
# For deployment, set DJANGO_DEBUG=false.
DEBUG = os.environ.get(
    'DJANGO_DEBUG',
    'false'
).strip().lower() in {'true', '1', 'yes', 'on'}


# SECRET_KEY must come from an environment variable in production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if SECRET_KEY == 'replace_with_a_random_secret':
    SECRET_KEY = None

if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is disabled.'
        )

    # Local development fallback only.
    SECRET_KEY = secrets.token_urlsafe(50)


# ============================================================
# ALLOWED HOSTS
# ============================================================

configured_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')

ALLOWED_HOSTS = (
    [host.strip() for host in configured_hosts.split(',') if host.strip()]
    if configured_hosts.strip()
    else ['127.0.0.1', 'localhost', 'testserver']
)


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

configured_csrf_origins = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    ''
)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in configured_csrf_origins.split(',')
    if origin.strip()
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'emails',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'email_classifier.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'email_classifier.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory used by collectstatic during deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# PRODUCTION SECURITY
# ============================================================

# These are enabled only when DEBUG is disabled.
# This prevents local development from being affected.

if not DEBUG:
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True


# ============================================================
# EMAIL
# ============================================================

# Production-ready SMTP configuration.
# Email credentials must be supplied through environment variables.
#
# Example environment variables:
#
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_HOST_USER=your_email@gmail.com
# EMAIL_HOST_PASSWORD=your_app_password
# EMAIL_USE_TLS=true

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'HOST': os.environ.get('EMAIL_HOST', ''),
        'PORT': int(os.environ.get('EMAIL_PORT', '587')),
        'USERNAME': os.environ.get('EMAIL_HOST_USER', ''),
        'PASSWORD': os.environ.get('EMAIL_HOST_PASSWORD', ''),
        'USE_TLS': os.environ.get(
            'EMAIL_USE_TLS',
            'true'
        ).strip().lower() in {'true', '1', 'yes', 'on'},
    },
}


# ============================================================
# LOGGING
# ============================================================

# Emit only the service's explicitly sanitized diagnostics
# in the Django terminal.
#
# API keys and headers are never included in these records.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'provider_diagnostics': {
            'format': '{message}',
            'style': '{',
        },
    },

    'handlers': {
        'provider_console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'provider_diagnostics',
        },
    },

    'loggers': {
        'emails.views': {
            'handlers': ['provider_console'],
            'level': 'INFO',
            'propagate': False,
        },

        'emails.ai_service': {
            'handlers': ['provider_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}